### ISSUE TITLE
Feature proposition - selecting text

### ISSUE THREAD

**Issue by amiroslaw** [lalitmee/browse.nvim#14]
Do you consider adding the ability to search from a selected text like in this plugin:
https://github.com/voldikss/vim-browser-search

**Comment by lalitmee** [comment]
@amiroslaw, sure. But I don't have time to work on this. PR is always welcome.

**Comment by phanen** [comment]
@amiroslaw @lalitmee I create a pr(https://github.com/lalitmee/browse.nvim/pull/16) to directly put visual text into search box.
Hope it can be of help.

**Comment by lalitmee** [comment]
@phanen, thanks for your PR. It really helps.

**Comment by lalitmee** [comment]
Fixed in #16
