### ISSUE TITLE
Can you make the autocomplete for bookmarks also have the alias and/or the grouped?

### ISSUE THREAD

**Issue by NikolaM-Dev** [lalitmee/browse.nvim#19]
It is great to be able to assign aliases or group the bookmarks but if these are not included in the search engine trigger nothing will be achieved because I will also have to remember keywords within the url to use the search

![image](https://github.com/lalitmee/browse.nvim/assets/62358156/746e79bc-3ada-45f5-84ee-4b33053eced5)

**Comment by lalitmee** [comment]
@NikolaM-Dev, what do you mean? I am not able to understand. 

For me, it works as expected.
![image](https://github.com/lalitmee/browse.nvim/assets/10762218/a5856acf-8012-4103-bc58-a7d2f7d5b692)

I know that I want to open `pull requests` so I searched for `pull` and it comes on the top.

Can you please elaborate on what do you want it to show or do?

**Comment by NikolaM-Dev** [comment]
@lalitmee What I want to tell you is that it only works if the payload in your `pull` example works because it is part of the URL, but not because it is recognizing your aliases.

I'll show you a little bit of the problem, I'm literally using your same config (just change the browser) and I added the aliases that I want to search to see the problem, if I also do the `pull`, you get the same result

![image](https://github.com/lalitmee/browse.nvim/assets/62358156/0ca435af-ed04-4d32-b2cb-54b6cc1b2b5d)

But if I use the payload `parq` it does not appear and this is because `parq` is not part of the url and therefore does not enter the search

![image](https://github.com/lalitmee/browse.nvim/assets/62358156/b50d05ac-cdf0-4cbd-84bf-cfaeb3e98684)

**Comment by lalitmee** [comment]
@NikolaM-Dev, I got it. I can't say that when I will be able to look at this. Little bit busy in work.

If you would like to tackle this by your own, then you are most welcome to raise the PR.

On the other hand I will try my best to look at this as early as possible.

**Comment by NikolaM-Dev** [comment]
@lalitmee Thank you very much, I totally understand your situation since I also have abandoned my config due to the same situation.
I am an nvim enthusiast and I would like to make my own plugins and so on but the truth is that I am not immersed in the subject to do so, in the same way I will try to see if I can make a solution
