### ISSUE TITLE
Can you make this configurable

### ISSUE THREAD

**Issue by ChristianChiarulli** [lalitmee/browse.nvim#2]
https://github.com/lalitmee/browse.nvim/blob/977c0ce69e3020ac4d317c0fd2fd27584566c567/lua/browse/input.lua#L11

**Comment by lalitmee** [comment]
@ChristianChiarulli, I was also thinking of making the `provider` configurable. I will try to make it configurable as soon as I get the time. 

If you really need this right now, PR is welcome.

**Comment by lalitmee** [comment]
Feature added in this [commit](https://github.com/lalitmee/browse.nvim/commit/c32c36a40cd1795359a8189d32cb724a6c7c0292)
