### ISSUE TITLE
Mac os wrong devdocs encoded url

### ISSUE THREAD

**Issue by Muslik** [lalitmee/browse.nvim#3]
In mac os open command with filetype gets wrong url:

For example if i exec command ```open 'https://devdocs.io/#q=lua table'``` it gets converted to ```https://devdocs.io/%23q=lua%20table``` instead of ```https://devdocs.io/#q=lua%20table``` and i get 404 error.

By the way if i exec ```open 'https://devdocs.io/#q=table'``` it doesn't encode and i get correct url.

**Comment by Muslik** [comment]
Maybe one of solution can be to encode url before it gets to open command...

**Comment by lalitmee** [comment]
@Muslik, you may be right. But I will have to see if that's what causing the problem or something else.

If you think that's the solution, you can raise a PR with that.

**Comment by lalitmee** [comment]
Hey @Muslik, you raised the PR but closed it. May I ask why?

**Comment by lalitmee** [comment]
closing this in favour of #8
