### ISSUE TITLE
bug: Error on calling the lua functions

### ISSUE THREAD

**Issue by yalikebaz** [lalitmee/browse.nvim#9]
Unsure if I'm doing something wrong but everytime I try calling `require('browse').input_search()` I get an error: 
`E5108: Error executing lua vim/shared.lua:0: Expected table, got string
stack traceback:
        [C]: in function 'assert'
        vim/shared.lua: in function 'tbl_isempty'
        ...ew/Cellar/neovim/0.8.1/share/nvim/runtime/lua/vim/ui.lua:90: in function 'input'
        .../site/pack/packer/start/browse.nvim/lua/browse/utils.lua:58: in function 'search'
        .../site/pack/packer/start/browse.nvim/lua/browse/utils.lua:71: in function 'input_search'
        [string ":lua"]:1: in main chunk`

This was working for me earlier, unsure what's going on.

**Comment by lalitmee** [comment]
@ShaySS, can you try with a minimal config?

I am not able to reproduce the issue.
